In [165]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import pickle

In [167]:
import pandas as pd

In [169]:
df=pd.read_csv('customer_shopping_behavior.csv')

In [171]:
df.head(10) #to see top 10 records

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [173]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [177]:
df.isnull().sum() #here we are finding sum of missing values

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [179]:
df.columns=df.columns.str.lower()#to convert column names into lower case
df.columns=df.columns.str.replace(' ','_')

In [181]:
df.columns #to print the column names

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [183]:
df.shape #this is a function used to find number of rows and columns

(3900, 18)

In [185]:
#to shorten the column name purchase_amount_(usd)
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [187]:
df.columns #to print the column names

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [189]:
#dropping unwanted columns
df = df.drop(columns=["item_purchased", "color", "location"], errors='ignore')

In [191]:
df.columns #to print the column names

Index(['customer_id', 'age', 'gender', 'category', 'purchase_amount', 'size',
       'season', 'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [193]:
#creating a target variable
df['Spender_Type'] = pd.cut(
    df['purchase_amount'],
    bins=[0, 50, 100, 1000],
    labels=[0, 1, 2]   # 0=Low, 1=Medium, 2=High
)

In [195]:
le = LabelEncoder()

categorical_cols = [
    'gender', 'category', 'size', 'season',
    'shipping_type', 'payment_method'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [197]:
df['subscription_status'] = df['subscription_status'].map({'Yes':1, 'No':0})
df['discount_applied'] = df['discount_applied'].map({'Yes':1, 'No':0})
df['promo_code_used'] = df['promo_code_used'].map({'Yes':1, 'No':0})

In [199]:
freq_map = {
    'Weekly': 4,
    'Fortnightly': 2,
    'Monthly': 1,
    'Quarterly': 0.5,
    'Annually': 0.1
}

df['frequency_of_purchases'] = df['frequency_of_purchases'].map(freq_map)

In [201]:
X = df.drop(columns=["Spender_Type", "purchase_amount"])
y = df["Spender_Type"]

In [203]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [205]:
feature_columns = X.columns

In [207]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [209]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [211]:
X = pd.get_dummies(X)
feature_columns = X.columns

In [213]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.573076923076923
              precision    recall  f1-score   support

           0       0.46      0.12      0.19       326
           1       0.59      0.90      0.71       454

    accuracy                           0.57       780
   macro avg       0.52      0.51      0.45       780
weighted avg       0.53      0.57      0.49       780

In [215]:
X = df.drop(columns=["Spender_Type", "purchase_amount"])
y = df["Spender_Type"]

X = pd.get_dummies(X)
feature_columns = X.columns

In [217]:
pickle.dump(feature_columns, open("features.pkl", "wb"))

In [219]:
pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

In [221]:
def predict_customer(input_dict):
    input_df = pd.DataFrame([input_dict])
    
    input_df = pd.get_dummies(input_df)
    
    input_df = input_df.reindex(columns=feature_columns, fill_value=0)
    
    input_scaled = scaler.transform(input_df)
    
    prediction = model.predict(input_scaled)[0]
    
    return prediction

In [223]:
feature_columns = pickle.load(open("features.pkl", "rb"))

In [225]:
sample_input = {
    'age': 25,
    'gender': 1,
    'category': 2,
    'size': 1,
    'season': 0,
    'review_rating': 4.5,
    'subscription_status': 1,
    'discount_applied': 1,
    'promo_code_ysed': 0,
    'previous_purchases': 10,
    'payment_method': 2,
    'shipping_type': 1,
    'frequency_of_purchases': 4
}

In [227]:
result = predict_customer(sample_input)

label_map = {0: "Low", 1: "Medium", 2: "High"}

print("Customer is:", label_map[result], "spender")

Customer is: Medium spender